Repository asAshuKulu/Hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#2 Binary_Search.cpp
  Binary_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#3 Create binarytree.c
  binarytree.c
Labels: good first issue, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted, hacktoberfestaccepted, hacktoberfest-2021

#39 Binary Heap Sort
  BinaryHeapSort.java
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#42 Created code for Bucket Sort
  Bucket_Sort.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#41 heapsort in cpp
  heapsort.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#40 added quicksort
  quicksort.py
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#45 Create ShortestCommonSupersequence.cpp
  shortest common supersequence.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#44 added kmp string algorithm
  KMP_algo.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#43 Added fibonacci in c++
  C++fibonacci.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted
